services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evo_pass
      POSTGRES_DB: evolution
    volumes:
      - ./evo-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: evolution_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_API_KEY: supersecretkey
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://evolution:evo_pass@postgres:5432/evolution?schema=public
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: redis://redis:6379
      CONFIG_SESSION_PHONE_VERSION: 2.3000.1023204200
      WEBHOOK_GLOBAL_URL: https://your-render-service.onrender.com/webhook
    # volumes:
    #   - ./evolution_instances:/evolution/instances
    #   - ./evolution_config:/evolution/config
    # restart: unless-stopped
